# Generated by Django 5.1 on 2025-06-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loyalty", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="phone",
        ),
    ]
