# Generated by Django 5.2.1 on 2025-05-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_category_parent_product_is_featured"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "商品分類",
                "verbose_name_plural": "商品分類",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.IntegerField(default=0, verbose_name="排序順序"),
        ),
    ]
