# Generated by Django 5.2.1 on 2025-05-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_category_options_category_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="新上市商品"),
        ),
    ]
