# Generated by Django 5.2.1 on 2025-05-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-is_new", "category__order", "name"],
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
            },
        ),
    ]
