# Generated by Django 5.2.1 on 2025-05-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.TextField(blank=True, verbose_name="商品成分"),
        ),
    ]
